Create dabase mydb --Tables will be created by default while starting application (hibernate capability);
use mydb --dabase=mydb user=root, password=1234;
insert into client(nom,capital,adresse) values('Mickel Stairs',10000,'USA'); 
insert into client(nom,capital,adresse) values('Jean Walless',20000,'UK');
insert into client(nom,capital,adresse) values('Juliette Robine',30000,'France');
insert into Produit(libelle,qtstock,prix) values('TV Smart 15p',15,13000);
insert into Produit(libelle,qtstock,prix) values('Imprimante Laser',17,1750);
insert into Produit(libelle,qtstock,prix) values('PC portable',25,7500);
insert into Produit(libelle,qtstock,prix) values('Machine à laver',27,9500);
insert into Produit(libelle,qtstock,prix) values('Machine à laver',27,9500);
insert into Produit(libelle,qtstock,prix) values('Machine à coudre',0,4000);
